config/routes.rb
Rails.application.routes.draw do
  resources :places
  root 'places#index'

  resources :api do
    collection do
      get 'get_nearby_places'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	belongs_to :country
	belongs_to :state
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :states
end

app/models/place.rb
class Place < ApplicationRecord
	acts_as_mappable :default_units => :miles,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :latitude,
                   :lng_column_name => :longitude

   belongs_to :country
   belongs_to :state
   belongs_to :city

  def self.get_nearby_places(latitude, longitude, units, distance)
  	places_hash = {}
  	places_hash["response"] ||= {}
  	places = Place.includes(:city, :state, :country).within(distance.to_f, :units => units.to_sym, :origin => [latitude, longitude])
  	if places.present?
  		places.each do |place|
  			places_hash["response"]["#{place.name}"] = {'Place name' => place.name, "Place Type" => place.place_type, "Latitude" => place.latitude, "Longitude" => place.longitude, "Location" => place.address, "City" => place.city.name, "State" => place.state.name, "Country" => place.country.name}
  		end
  	else
  		places_hash["response"] = "No places found near to the given latitude and longitude"
  	end
  	places_hash
  end

end

app/models/state.rb
class State < ApplicationRecord
	has_many :cities
	belongs_to :country
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

	# rescue_from Execption
  rescue_from 'ApiException' do |exception|
    render json: error_result_hash(exception.code, exception.error_message)
  end

  def error_result_hash(resp_code, resp_message)
    er_hash = {'response' => {'code' => resp_code, 'message' => resp_message}}
    er_hash
  end

  def generate_success_response_hash(status, message)
    er_hash = {'response' => {'code' => status, 'message' => message}}
    render_json_hash(er_hash)
  end

  def render_json_hash(resp_hash)
    render json: hash_to_json(resp_hash), status: 200
  end

  def hash_to_json(hash_obj)
    Oj.dump(hash_obj)
  end

	def get_nearby_places
		if params[:location].present? && (params[:latitude].blank? && params[:longitude].blank?)
			params[:latitude], params[:longitude] = Place.where(address: params[:location]).pluck(:latitude, :longitude).first 
			raise ApiException.new(500, 'No data found for this location') if params[:latitude].blank? && params[:longitude].blank?

		end
		validate_request
		respond_to do |format|
			# By default units is considered as kms. However user can pass either miles or kms
			units = params[:units].present? ? params[:units] : "kms"
			# By default radius is considered as 10. However user can pass any radius
			radius = params[:radius].present? ? params[:radius].to_f : 10
			resp_hash = Place.get_nearby_places(params[:latitude], params[:longitude], units, radius)
			format.json {render_json_hash(resp_hash)}
			format.html {render text: 'Access Denied', status: 401}
		end
	end

	def validate_request
		raise ApiException.new(400, 'Not a Valid Request') unless request.get?
		raise ApiException.new(500, 'Please send either Longitude and Latitude or Location') if (params[:latitude].blank? || params[:longitude].blank?)

	end
end

class ApiException < Exception
  attr_accessor :code, :error_message

  def initialize(code, error_message)
    @code, @error_message = code, error_message
    er_hash = {'response' => {'code' => code, 'message' => error_message}}
    super(error_message)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.includes(:city, :state, :country).all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
    get_country_state_and_city
  end

  # GET /places/1/edit
  def edit
    get_country_state_and_city
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :address, :latitude, :longitude, :state_id, :city_id, :country_id, :place_type)
    end

    def get_country_state_and_city
      @countries = Country.all.pluck(:name, :id)
      @states = State.all.pluck(:name, :id)
      @cities = City.all.pluck(:name, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse"">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Location Finder</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%#= link_to "Sign in",login_path %>
        </li>
        <li>
          <%#= link_to "Sign up",signup_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GridApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header id="header">
      <%= render :partial=> "/layouts/header" %>
    </header>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

  </body>
</html>

app/views/places/_form.html.erb
<%= bootstrap_form_for(place) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, required: true %>
  </div>

  <div class="field">
    <%= form.text_field :place_type, required: true %>
  </div>

  <div class="field">
    <%= form.text_field :address, label: "Location", required: true %>
  </div>

  <div class="field">
    <%= form.text_field :latitude, required: true %>
  </div>

  <div class="field">
    <%= form.text_field :longitude, required: true %>
  </div>

  <div class="field">
    <%= form.select :country_id, @countries, { label: "Choose your Country" }, { class: "selectpicker" } %>
  </div>

  <div class="field">
    <%= form.select :state_id, @states, { label: "Choose your State" }, { class: "selectpicker" } %>
  </div>

  <div class="field">
    <%= form.select :city_id, @cities, { label: "Choose your City" }, { class: "selectpicker" } %>
  </div>
 
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Places</h1>
<div align="right" style="margin-bottom: 20px;">
  <%= link_to 'New Place', new_place_path, :class => "btn btn-primary" %>
</div>
<div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Place type</th>
        <th>Location</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>State</th>
        <th>City</th>
        <th>Country</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% if @places.present? %>
        <% @places.each do |place| %>
          <tr>
            <td><%= place.name %></td>
            <td><%= place.place_type %></td>
            <td><%= place.address %></td>
            <td><%= place.latitude %></td>
            <td><%= place.longitude %></td>
            <td><%= place.state.name %></td>
            <td><%= place.city.name %></td>
            <td><%= place.country.name %></td>
            <td><%= link_to 'Show', place %></td>
            <td><%= link_to 'Edit', edit_place_path(place) %></td>
            <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="11">
            <span align="center">No Data Found</span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @place.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<p>
  <strong>City:</strong>
  <%= @place.city.name %>
</p>


<p>
  <strong>State:</strong>
  <%= @place.state.name %>
</p>


<p>
  <strong>Country:</strong>
  <%= @place.country.name %>
</p>

<p>
  <strong>Place type:</strong>
  <%= @place.place_type %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>